### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by DiesIrae** [DiesIrae/xstate-game-of-life#1]
- [x] Remove `nextBoard`, integrate next state to cells (V2)
- [ ] Replace jquery with React (V3)
- [ ] Try to remove impurity (access state from outside function)
