### ISSUE TITLE
Interface ideas & roadmap

### ISSUE THREAD

**Issue by DiesIrae** [DiesIrae/xstate-game-of-life#2]
- [ ] Replace jQuery with React
- [ ] Add buttons to control pulse: play, stop, step
- [ ] Add an "paint initial board" phase, where we can toggle life/death on initial board by clicking on it
